
export default [
	{
		"id" : "1",
		"nom": "ahadri",
		"prenom": "hatim",
		"details": "The first profile in the app",
		"promo": "2017",
		"ville": "paris",
		"pays": "France",
		"entreprise_universite": "BNP Paris bas",
		"poste": "Full Stack Consultant ",
		"filiere ": "GL",
		"featured": true,
		"laureat": true,
		"student": false,
		"linkedIn": "https://www.linkedin.com/in/hatim-ahadri/",
		"image" : "https://media.licdn.com/dms/image/C4E03AQEUSJ_sSzjcIw/profile-displayphoto-shrink_200_200/0?e=1580947200&v=beta&t=cNSoOoWK2tamtP-9HJgWK6TLgFM0bT6pqwR1pmdJc4A",
		"keywords": "data, SQL SERVER, ORACLE Database"
	},
	{
		"id" : "2",
		"nom": "ahmadoun",
		"prenom": "douae",
		"promo": "2017",
		"ville": "paris",
		"pays": "France",
		"details": "The second profile in the app",
		"entreprise_universite": "Université Paris Descartes",
		"poste": "Phd student",
		"filiere": "GL",
		"featured" : true,
		"laureat": true,
		"student": false,
		"linkedIn": "https://www.linkedin.com/in/douae-ahmadoun/",
		"image" : "https://media.licdn.com/dms/image/C4D03AQFc4oTRoPRSJA/profile-displayphoto-shrink_200_200/0?e=1580947200&v=beta&t=TOAYqUx3Kw3FDy7sutYkK_HL5_UyohAaTzoZkUrW2Gg"
	},
	{
		"nom": "alehyen",
		"prenom": "Ismail",
		"promo": "2017",
		"ville": "Rabat",
		"pays": "Maroc",
		"entreprise_universite": "Quinten",
		"poste": "Software Engineer",
		"filiere": "GL",
		"linkedIn": "https://www.linkedin.com/in/ismail-alehyen/",
		"image": "https://media.licdn.com/dms/image/C4D03AQFcUaS629WDBw/profile-displayphoto-shrink_200_200/0?e=1580947200&v=beta&t=LiCpPAO2aS5t7OpmtFyf2enn-aPv4buY5fDu7xeN_uI",
		"featured" : true,
		"laureat": true,
		"student": false,
		"id": "3",
		"details": "this is the third one"
	}/*,
	{
		"nom": "allak",
		"prenom": "Aymane Khalid ",
		"promo": "2017",
		"ville": "paris",
		"pays": "France",
		"entreprise/université": "Gfi informatique",
		"poste": "Software Engineer",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/aymane-khalid-allak-93495711a/",
		"image": "https://media.licdn.com/dms/image/C4D03AQFcUaS629WDBw/profile-displayphoto-shrink_200_200/0?e=1580947200&v=beta&t=LiCpPAO2aS5t7OpmtFyf2enn-aPv4buY5fDu7xeN_uI",
		"featured" : true,
		"id": "3",
		"details": "this is the third one"
	}*/,
	{
		"nom": "amal",
		"prenom": "El mahdi",
		"promo": "2017",
		"ville": "casablanca",
		"pays": "Maroc",
		"entreprise_universite": "Payment Center For Africa ",
		"poste": "Full Stack Developer",
		"filiere": "GL",
		"linkedIn": "https://www.linkedin.com/in/el-mehdi-amal-17bb09133/",
		"image": "https://media.licdn.com/dms/image/C4D03AQH7-ZX5hGDC4Q/profile-displayphoto-shrink_200_200/0?e=1580947200&v=beta&t=AasSDRwijmeVO8jcgpJYdnSbi9QNkOiUeyRyohShaXk",
		"featured" : true,
		"laureat": true,
		"student": false,
		"id": "4",
		"details": "this is the fourth one"
	},
	{
		"nom": "amine",
		"prenom": "rida",
		"promo": "2017",
		"ville": "casablanca",
		"pays": "Maroc",
		"entreprise_universite": "Akka Technologies",
		"poste": "Team Lead",
		"filiere": "GL",
		"linkedIn": "https://www.linkedin.com/in/rida-amine-33ba8ba8/",
		"featured" : true,
		"laureat": true,
		"student": false,
		"id": "5",
		"details": "this is the fourth one"
	},
	{
		"nom": "amine",
		"prenom": "taha",
		"promo": "2017",
		"ville": "casablanca",
		"pays": "Maroc",
		"entreprise_universite": "Akka Technologies",
		"poste": "Software Engineer",
		"filiere": "GL",
		"linkedIn": "https://www.linkedin.com/in/taha-amine-10731b115/",
		"image": "",
		"featured" : true,
		"laureat": true,
		"student": false,
		"id": "6",
		"details": "this is the fourth one"
	},
	{
		"nom": "arajoum",
		"prenom": "ilyasse",
		"promo": "2017",
		"ville": "paris",
		"pays": "France",
		"entreprise_universite": "VINCI Autoroutes",
		"poste": "DevOps engineer",
		"filiere": "GL",
		"linkedIn": "https://www.linkedin.com/in/ilyasse-arajoum-7b115610b/",
		"image": "",
		"featured" : true,
		"laureat": true,
		"student": false,
		"id": "7",
		"details": ""
	},
	{
		"nom": "arrad",
		"prenom": "Hamza",
		"promo": "2017",
		"ville": "casablanca",
		"pays": "Maroc",
		"entreprise_universite": "Gfi informatique",
		"poste": "Java/Java EE Consultant",
		"filiere": "GL",
		"linkedIn": "https://www.linkedin.com/in/arrad-hamza-125683a0/",
		"image": "",
		"featured" : true,
		"laureat": true,
		"student": false,
		"id": "8",
		"details": " Java/Java EE Consultant on PLM Windchill chez Gfi Informatique "
	},
	{
		"nom": "arzmi",
		"prenom": "imad",
		"promo": "2017",
		"ville": "casablanca",
		"pays": "Maroc",
		"entreprise_universite": "OCP",
		"poste": "Full Stack Developer",
		"filiere": "GL",
		"linkedIn": "https://www.linkedin.com/in/arzmi-imad-83235a116/",
		"image": "",
		"featured" : true,
		"laureat": true,
		"student": false,
		"id": "9",
		"details": " Java/Java EE Consultant on PLM Windchill chez Gfi Informatique "
	},
	{
		"nom": "azouggarh",
		"prenom": "chaymae",
		"promo": "2017",
		"ville": "casablanca",
		"pays": "Maroc",
		"entreprise_universite": "OCP",
		"poste": "Financial Digitization Analyst",
		"filiere": "GL",
		"linkedIn": "https://www.linkedin.com/in/chaymae-azouggarh-a76a73116/",
		"image": "https://media.licdn.com/dms/image/C5103AQFz4S2347H2dA/profile-displayphoto-shrink_200_200/0?e=1580947200&v=beta&t=GDRErzTjmfD-1nQw6hCWcfsN16Vp4Tp4sTN0C21z7IE",
		"featured" : true,
		"laureat": true,
		"student": false,
		"id": "10",
		"details": " Java/Java EE Consultant on PLM Windchill chez Gfi Informatique "
	},
	{
		"nom": "azaroual",
		"prenom": "anas",
		"promo": "2017",
		"ville": "casablanca",
		"pays": "Maroc",
		"entreprise_universite": "Nimble Ways",
		"poste": "Full Stack Developer",
		"filiere": "GL",
		"linkedIn": "https://www.linkedin.com/in/anas-azaroual-8556a4132/",
		"image": "https://media.licdn.com/dms/image/C5603AQEhudZ_5m6nUw/profile-displayphoto-shrink_200_200/0?e=1580947200&v=beta&t=UEzHSX0oeeiONvWfwXfqBSj_4NYZOO_jIlGRDJ3mzm4",
		"featured" : true,
		"laureat": true,
		"student": false,
		"id": "11",
		"details": " Java/Java EE Consultant on PLM Windchill chez Gfi Informatique ",
		"keywords": "Git, Data Analysis, Python"
	},
	{
		"nom": "baamrani",
		"prenom": "khadija",
		"promo": "2017",
		"ville": "casablanca",
		"pays": "Maroc",
		"entreprise_universite": "Harman international",
		"poste": "Software Engineer",
		"filiere": "GL",
		"linkedIn": "https://www.linkedin.com/in/khadija-baamrani-b7b457121/",
		"image": "https://media.licdn.com/dms/image/C5103AQFLhM_sXpw8uw/profile-displayphoto-shrink_200_200/0?e=1580947200&v=beta&t=sE2Lx-ys1lP81HRAfGDJT8loOTwEL8vSzQ2Dc48V34c",
		"featured" : true,
		"laureat": true,
		"student": false,
		"id": "12",
		"details": " Pas de details",
		"keywords": "PHP, Symphony, Gestion de projet, Scrum"
	}]/*,
	{
		"nom": "Bougarfaoui",
		"prenom": "El Houcine ",
		"promo": "2017",
		"ville": "Rabat",
		"pays": "Maroc",
		"entreprise/université": "scale",
		"poste": "Software Engineer",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/el-houcine-bougarfaoui-09a72b131/"
	},
	{
		"nom": "boughti",
		"prenom": "houssam",
		"promo": "2017",
		"ville": "Rabat",
		"pays": "Maroc",
		"entreprise/université": "SQLI",
		"poste": "Software Engineer",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/houssam-boughti/"
	},
	{
		"nom": "CHRIFI ALAOUI",
		"prenom": "hakim",
		"promo": "2017",
		"ville": "casablanca",
		"pays": "Maroc",
		"entreprise/université": "OCTO Technologies",
		"poste": "Consultant DevOps",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/hakimchrifialaoui/"
	},
	{
		"nom": "daoudi",
		"prenom": "wissal",
		"promo": "2017",
		"ville": "Rabat",
		"pays": "Maroc",
		"entreprise/université": "HP",
		"poste": "Presales Technical Consultant",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/wissal-daoudi-4b07b6129/"
	},
	{
		"nom": "el aasri",
		"prenom": "aicha",
		"promo": "2017",
		"ville": "paris",
		"pays": "France",
		"entreprise/université": "Amaris",
		"poste": "Consultant",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/aicha-el-aasri-b7477b123/"
	},
	{
		"nom": "El aoula ",
		"prenom": "fatima zahra",
		"promo": "2017",
		"ville": "paris",
		"pays": "France",
		"entreprise/université": "Dauphine",
		"poste": "MIAGE student",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/fatima-zahra-el-aoula-a19195129/"
	},
	{
		"nom": "el bouazzaoui",
		"prenom": "wafaa",
		"promo": "2017",
		"ville": "paris",
		"pays": "France",
		"entreprise/université": "Dauphine",
		"poste": "MIAGE student",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/wafaa-el-bouazzaoui-917270a8/"
	},
	{
		"nom": "el massi ",
		"prenom": "hamza",
		"promo": "2017",
		"ville": "casablanca",
		"pays": "Maroc",
		"entreprise/université": "Nimble Ways",
		"poste": "Consultant JS",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/hamzaelmassi/"
	},
	{
		"nom": "el meftouhi",
		"prenom": "soufiane",
		"promo": "2017",
		"ville": "paris",
		"pays": "France",
		"entreprise/université": "BNP Paris bas",
		"poste": "Tech Lead en Angular",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/soufian-el-meftouhi-ab183ba2/"
	},
	{
		"nom": "el mesaoudi",
		"prenom": "zakariae",
		"promo": "2017",
		"ville": "Rabat",
		"pays": "Maroc",
		"entreprise/université": "OCTO Technologies",
		"poste": "Consultant IT",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/zakariae-el-mesaoudi-235890105/"
	},
	{
		"nom": "elaffani",
		"prenom": "marwa",
		"promo": "2017",
		"ville": "paris",
		"pays": "France",
		"entreprise/université": "Dauphine",
		"poste": "MIAGE student",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/marwa-elaffani-566767a2/"
	},
	{
		"nom": "enaija",
		"prenom": "Abderrafiâ",
		"promo": "2017",
		"ville": "paris",
		"pays": "France",
		"entreprise/université": "Dataraise",
		"poste": "Consultant Talend",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/abderrafi%C3%A2-enaija/"
	},
	{
		"nom": "et-tayyeb",
		"prenom": "walid",
		"promo": "2017",
		"ville": "paris",
		"pays": "France",
		"entreprise/université": "Groupe alties ",
		"poste": "Consultant Mainframe-COBOL",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/walid-et-tayyeb-087a68124/"
	},
	{
		"nom": "fadyl",
		"prenom": "brahim",
		"promo": "2017",
		"ville": "casablanca",
		"pays": "Maroc",
		"entreprise/université": "Akka Technologies",
		"poste": "lead developer",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/brahim-fadyl/"
	},
	{
		"nom": "fliou",
		"prenom": "salim",
		"promo": "2017",
		"ville": "montréal",
		"pays": "canada",
		"entreprise/université": "optimum solutions TI",
		"poste": "Concepteur Développeur",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/salim-fliou-65a536b9/"
	},
	{
		"nom": "gamrani",
		"prenom": "hajar",
		"promo": "2017",
		"ville": "paris",
		"pays": "France",
		"entreprise/université": "Margo",
		"poste": "Software Consultant",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/hajar-gamrani-201938a3/"
	},
	{
		"nom": "hadouchi",
		"prenom": "khalid",
		"promo": "2017",
		"ville": "Rabat",
		"pays": "Maroc",
		"entreprise/université": "Orange business maroc",
		"poste": "Oracle ERP Cloud Software Engineer",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/khalid-haddouchi-236901a6/"
	},
	{
		"nom": "Halim",
		"prenom": "hanane",
		"promo": "2017",
		"ville": "casablanca",
		"pays": "Maroc",
		"entreprise/université": "Société Générale - CIB",
		"poste": "Capital Market R&D Engineer",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/hhalim/"
	},
	{
		"nom": "hamane",
		"prenom": "ishaq",
		"promo": "2017",
		"ville": "casablanca",
		"pays": "Maroc",
		"entreprise/université": "Payment Center For Africa ",
		"poste": "Full Stack Developer",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/ishaq-hamane-6b23a4127/"
	},
	{
		"nom": "hanzaz ",
		"prenom": "sophia",
		"promo": "2017",
		"ville": "Rabat",
		"pays": "Maroc",
		"entreprise/université": "Capgemini",
		"poste": "Applications manager",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/sophia-hanzaz-86886a140/"
	},
	{
		"nom": "ibn omar",
		"prenom": "ismael",
		"promo": "2017",
		"ville": "paris",
		"pays": "France",
		"entreprise/université": "Natixis",
		"poste": "Data Scientist",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/ismaelibnomar/"
	},
	{
		"nom": "karnas",
		"prenom": "anoir",
		"promo": "2017",
		"ville": "Rabat",
		"pays": "Maroc",
		"entreprise/université": "Capgemini",
		"poste": "Ingénieur étude et développement",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/anoir-karnas-361a86119/"
	},
	{
		"nom": "Massemoue",
		"prenom": "imad",
		"promo": "2017",
		"ville": "casablanca",
		"pays": "Maroc",
		"entreprise/université": "Spacebyte AG",
		"poste": "Software Engineer",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/imad-massemoue/"
	},
	{
		"nom": "Moussaif",
		"prenom": "ghassan",
		"promo": "2017",
		"ville": "paris",
		"pays": "France",
		"entreprise/université": "Margo",
		"poste": "Java/Java EE Consultant",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/ghassanmoussaif/"
	},
	{
		"nom": "naji amrani",
		"prenom": "akram",
		"promo": "2017",
		"ville": "Rabat",
		"pays": "Maroc",
		"entreprise/université": "Synaptique Maghreb",
		"poste": "Software Engineer",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/akram-naji-amrani-691376127/"
	},
	{
		"nom": "nouar",
		"prenom": "Oumaima",
		"promo": "2017",
		"ville": "paris",
		"pays": "France",
		"entreprise/université": "Audiense",
		"poste": "Consultant",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/oumaima-nouar-4940bba6/"
	},
	{
		"nom": "ouali",
		"prenom": "mouad",
		"promo": "2017",
		"ville": "casablanca",
		"pays": "Maroc",
		"entreprise/université": "Société Générale - ATS",
		"poste": "Financial markets research engineer",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/mouad-ouali-788493133/"
	},
	{
		"nom": "oubella",
		"prenom": "said",
		"promo": "2017",
		"ville": "Rabat",
		"pays": "Maroc",
		"entreprise/université": "DXC Technologies",
		"poste": "Consultant Technico-Fonctionnel",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/said-oubella-349b40122/"
	},
	{
		"nom": "rbigat",
		"prenom": "Ismail",
		"promo": "2017",
		"ville": "casablanca",
		"pays": "Maroc",
		"entreprise/université": "Payment Center For Africa ",
		"poste": "Full Stack Developer",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/ismail-rbigat-8463ab123/"
	},
	{
		"nom": "samari",
		"prenom": "fatima ezzahra",
		"promo": "2017",
		"ville": "paris",
		"pays": "France",
		"entreprise/université": "Ingenico Group",
		"poste": "Consultante scala",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/fatiha-reja-58087611a/"
	},
	{
		"nom": "srija",
		"prenom": "mehdi",
		"promo": "2017",
		"ville": "casablanca",
		"pays": "Maroc",
		"entreprise/université": "Sopra Banking Software",
		"poste": "Ingénieur étude et développement",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/mehdi-srija-510775132/"
	},
	{
		"nom": "takkal",
		"prenom": "mouad",
		"promo": "2017",
		"ville": "casablanca",
		"pays": "Maroc",
		"entreprise/université": "Payment Center For Africa ",
		"poste": "Full Stack Developer",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/takkal-mouad-346326120/"
	},
	{
		"nom": "tebbai",
		"prenom": "ayoub",
		"promo": "2017",
		"ville": "paris",
		"pays": "France",
		"entreprise/université": "Université Paris 13",
		"poste": "master student",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/ayoub-tebbai/"
	},
	{
		"nom": "zyane",
		"prenom": "rania",
		"promo": "2017",
		"ville": "Rabat",
		"pays": "Maroc",
		"entreprise/université": "OCTO Technologies",
		"poste": "consultant IT",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/raniazy/"
	},
	{
		"nom": "touzani",
		"prenom": "fadoua",
		"promo": "2017",
		"ville": "casablanca",
		"pays": "Maroc",
		"entreprise/université": "PayLogic",
		"poste": "Ingénieure de projets monétiques",
		"filiere ": "GL",
		"linkedIn": "https://www.linkedin.com/in/fadoua-touzani-ensias/"
	}
]

*/